export const MY_PROFILE = "/me";
export const REGISTER = "/register";
export const SIGN_IN = "/signin";
export {};
export const DRAFTED_LOADS = "/drafted_loads";
export const POSTED_LOADS = "/posted-loads";
export const SHIPPED_LOADS = "/shipped-loads";
export const ACTIVE_LOAD = "/active_load";
export const CREATE_TRUCK = "/create/truck";
// export const TRUCKS = "/trucks";
export const CREATE_LOAD = "/create/load";
// export const ONELOAD = "/load";
