export const MY_PROFILE = "/me";
export const REGISTER = "/register";
export const SIGN_IN = "/signin";
export {};
export const DRAFTED_LOADS = "/loads/drafted";
export const POSTED_LOADS = "/loads/posted";
export const SHIPPED_LOADS = "/loads/shipped";
export const ACTIVE_LOAD = "/active_load";
export const CREATE_TRUCK = "/truck/create";
// export const TRUCKS = "/trucks";
export const CREATE_LOAD = "/load/create";
export const ONE_LOAD = "/load";
